### ISSUE TITLE
Overwrite AuthToken on login

### ISSUE THREAD

**Issue by Morhafalaraj** [alvarosanchez/grails-spring-security-rest#170]
(Spring-security-rest)
Hey,
I am having issues overwriting a token for a user that already has a token.

Issue: POST request to api/v1/login generates new token in JSON-response, but the newly generated token that I recieve is not stored in database if we already have a token for that user, the old token remains until the quartz job remove it.

I expect the user to recieve a new token(and also store it) if the user logs in again.

Best regards
Morhaf

**Comment by alvarosanchez** [comment]
Is it a particular persistence issue you are seeing in the GORM implementation?

**Comment by Morhafalaraj** [comment]
@alvarosanchez Yes. The main issue is that if a user logs in two times, he will recieve a new token that is not stored in the database. The new token does not overwrite the "old" one. Maybe the stored token could be sent instead of a new token, because the new token is never persisted? I have read in the documentation but did not find an answer.. Thanks

Config.groovy:

    grails.plugin.springsecurity.rest.token.validation.useBearerToken = false
    grails.plugin.springsecurity.rest.token.validation.headerName = 'X-Auth-Token'
    grails.plugin.springsecurity.rest.login.endpointUrl = '/api/v1/login'
    grails.plugin.springsecurity.rest.token.storage.useGorm = true
    grails.plugin.springsecurity.rest.token.storage.gorm.tokenDomainClassName = 'backend.auth.AuthenticationToken'
    grails.plugin.springsecurity.rest.token.storage.gorm.tokenValuePropertyName = 'token'
    grails.plugin.springsecurity.rest.token.storage.gorm.usernamePropertyName = 'username'
    grails.plugin.springsecurity.rest.login.passwordPropertyName = 'password'
    grails.plugin.springsecurity.rest.login.useJsonCredentials = true
    grails.plugin.springsecurity.rest.login.useRequestParamsCredentials = false

**Comment by alvarosanchez** [comment]
The problem is that the behaviour you describe is not possible to implement given the existing plugin's interface. If you have a look at [`TokenStorageService`](https://github.com/alvarosanchez/grails-spring-security-rest/blob/develop/src/groovy/com/odobo/grails/plugin/springsecurity/rest/token/storage/TokenStorageService.groovy), there is no way to load a token by user, which is what you would need to implement the behaviour you described.

The GORM implementation is creating a new token because, as per the mentioned interface, there is no way to know if there is any existing token for such particular user.

And such method don't exist because it won't be possible to do it in the Memcached implementation.

However, at the end of the day everything are Spring beans, so you should be able to subclass and override what you want, and place your own implementations in `resources.groovy`.

Therefore I'm closing this issue.
