### ISSUE TITLE
Global OAuth Logout

### ISSUE THREAD

**Issue by donalmurtagh** [alvarosanchez/grails-spring-security-rest#191]
I don't think the OAuth spec includes this, but nevertheless it would be a very useful feature. The idea is that if a user logs into my site using Facebook OAuth, then when they logout they should also be given the option of logging out from Facebook. This would be useful if they logged into my site on a public computer.

It seems this is supported by most OAuth providers, the URLs for Facebook, Google and Microsoft are described [here](http://stackoverflow.com/a/17127388/2648).

I'm not sure whether this plugin or the `pac4j` library would be a more appropriate place to implement this?

**Comment by alvarosanchez** [comment]
Seems an easy feature to implement. I'll have a look at it

**Comment by domurtag** [comment]
It would be extremely useful. It's not straightforward to do this from a single-page app via AJAX because of CORS. Obviously you could simply do

    document.location = '"https://www.facebook.com/logout.php?next=http://myapp.com&access_token=xxx"

But this does a full page refresh, which will typically loses the current state of a SPA. It would be great if you specify a post-logout callback URL in `Config.groovy`, similar to the `frontendCallbackUrl` that is invoked after a successful OAuth login.

**Comment by alvarosanchez** [comment]
I don't have bandwidth at the moment to implement this. So I'm leaving this on hold.
