### ISSUE TITLE
Upgrade 1.4 to 1.5.1 note

### ISSUE THREAD

**Issue by rhodebump** [alvarosanchez/grails-spring-security-rest#218]
I recently upgraded from 1.4.0.RC5 to 1.5.1  Instead of getting 401 HTTP codes, I started getting 403

Once I commented out the following properties in Config.groovy, it worked again (got 401's)

grails.plugin.springsecurity.rest.token.validation.headerName = 'X-Auth-Token'
grails.plugin.springsecurity.rest.token.validation.useBearerToken = false1.4.0.RC5

Not a bug, but wanted to share.

**Comment by alvarosanchez** [comment]
Bearer token support was enabled by default already in 1.4.x: http://alvarosanchez.github.io/grails-spring-security-rest/1.4.1/docs/guide/whatsNew14.html

Maybe your issue was because you were not using a final release, but a release candidate. Never use RC's when stable ones are available (1.4.0 was released on 12 Aug 2014).
