### ISSUE TITLE
Can login be done with email and password?

### ISSUE THREAD

**Issue by lealceldeiro** [alvarosanchez/grails-spring-security-rest#335]
I'm using version 1.5.4 of this great plugin and I'd like to know if instead of doing _login_ with username and password of my login entity I could do it with email and password (email is another property of my login entity).

Is there any way I could change the property through which the plugin retrieves the username information?

**Comment by jresendiz27** [comment]
Hi! I think you can take a look to the docs, there's a way to handle your own json request.

[Docs](http://alvarosanchez.github.io/grails-spring-security-rest/latest/docs/#_extracting_credentials_from_the_request).

You can add your own implementation and use email instead of username. BTW, the `new UsernamePasswordAuthenticationToken(String username, String password)`, AFAIK it's part of the Spring Security Core, or create getters/setters for username but return email instead. 

I hope It helps!

Cheers.

**Comment by lealceldeiro** [comment]
Hi, Thanks! You were right! I implemented my own `DefaultJsonPayloadCredentialsExtractor`. It worked perfectly
