### ISSUE TITLE
Missing refresh_token on OAuth providers

### ISSUE THREAD

**Issue by pabloalba** [alvarosanchez/grails-spring-security-rest#337]
When I delegate the authentication to an external OAuth provider like google, the callback only gives me the access_token. When this access_token expires, how can I refresh it?

**Comment by alvarosanchez** [comment]
The access_token you get is not Google's, but Spring Security REST's. I evaluated the possibility to include a refresh_token in the response (#296), but because the delegation uses the OAuth 2.0 implicit grant, it wasn't possible to include it in the URL.

A potential solution would be to use authorization code grant (which would make Angular apps unable to fetch tokens without a backend), or to expose another endpoint to issue refresh tokens  in exchange of an access token.

Thoughts?

**Comment by alvarosanchez** [comment]
An existing workaround available today would be to use a stateful token storage (Memcached, Redis, etc) where tokens get refreshed on every check.

**Comment by pabloalba** [comment]
Yes I know that it is a Spring Security REST's token.

I see on #269 that you discard the refresh_token because of the size...

I like the idea of an endpoint to issue refresh tokens in exchange of an access token. I think I'll go with that.

Thank you
