### ISSUE TITLE
Creating users from social oauth2 login

### ISSUE THREAD

**Issue by volnei** [alvarosanchez/grails-spring-security-rest#387]
There's no documentation or example about how signup a user (and register it on own database) when user login from oauth2 like Google or Facebook. Can anyone provide an example?

**Comment by tiitkass** [comment]
Would like an example as well. So far I have only gathered that this could be done by custom implementation of `OauthUserDetailsService` but that is more of a hack than a proper solution.

**Comment by ottboy4** [comment]
It is a little hacky, but this is the general idea of how I do it.  In my config I assign a role for facebook or google so I know how to handle the data incoming here. I simply look to see if the user is already in the database and if they are I update the database record, otherwise I create a new one.

```
class MyOauthUserDetailsService implements OauthUserDetailsService {

    @Delegate
    UserDetailsService userDetailsService

    OauthUser loadUserByUserProfile(CommonProfile profile, Collection<GrantedAuthority> roles) throws UsernameNotFoundException {
        def isGoogle = roles*.authority.contains('ROLE_GOOGLE')

        // prefix with G or F for Google or Facebook
        def id = isGoogle ? "G${profile.id}" : "F${profile.id}"
        def oauthUser = new OauthUser(id, 'N/A', roles, profile)

        // find or create the user
        MyUserAccount user = MyUserAccount.findByUsername(oauthUser.username) ?: new UserAccount(oauthUser.username)

        // update the user info here (new or existing)
        if (isGoogle) {
            updateGoogleData(profile, user)
        } else {
            updateFacebookData(profile, user)
        }

        // save the user to the db
        user.save(failOnError: true)

        return oauthUser
    }
}
```

I also have another `UserDetailsService` which looks up the user in the database and uses my own `UserDetails` class to store the database user object on. That way I can access it later in my services.

**Comment by alvarosanchez** [comment]
Please post questions in [StackOverflow](http://stackoverflow.com/questions/tagged/grails+spring-security-rest). Label your questions with both the `grails` and `spring-security-rest` tags.

You can also try with asking in the [`#spring-security-rest` channel in Slack](https://grails.slack.com/messages/spring-security-rest).
